server:
  port: 8080
#  servlet:
#    context-path: /abc
spring:
  datasource:
    username: root
    password: 147258369
    url: jdbc:mysql://localhost:3308/abc
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
