server:
  port: 8080
  servlet:
    context-path: /abc
spring:
  datasource:
    name: root
    password: root
    url: jdbc:mysql://localhost:3306/abc
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
